name: Update Config

on:
  push:
    branches:
      - main

jobs:
  update_config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set API Key in JSON
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          sed -i "s/BASE_URL/${BASE_URL}/g" api-key.json
          sed -i "s/PUBLIC_KEY/${PUBLIC_KEY}/g" api-key.json
          sed -i "s/PRIVATE_KEY/${PRIVATE_KEY}/g" api-key.json

      - name: Commit and Push Changes
        run: |
          git config --global user.email "pktherock00@gmail.com"
          git config --global user.name "pktherock"
          git add api-key.json
          git commit -m "Update API key"
          git push origin main
