name: Update Config

on:
  push:
    branches:
      - main

jobs:
  update_config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set API Key in JSON
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          echo "BASE_URL secret value: ${{ secrets.BASE_URL }}"
          # Read the original JSON file
          ORIGINAL_JSON=$(cat api-key.json)

          # Use JavaScript to modify the JSON object with secret values
          NEW_JSON=$(node -e "
          const data = $ORIGINAL_JSON; 
          data.BASE_URL = '$BASE_URL'; 
          data.PUBLIC_KEY = '$PUBLIC_KEY'; 
          data.PRIVATE_KEY = '$PRIVATE_KEY'; 
          console.log(JSON.stringify(data));
          ")

          # Write the updated JSON back to the file
          echo "$NEW_JSON" > api-key.json

      - name: Commit and Push Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add api-key.json
          git commit -m "Update API key"
          git push origin main
